export const SYSTEM_MENUS = [
  {
    _id: 'm-ad',
    name: 'AdminDashboard',
    code: 'dashboard:admin',
    path: '/admin/dashboard',
    component: 'dashboard/AdminDashboard',
    type: 'menu',
    icon: 'Setting',
    sort: 10,
    meta: { title: 'System Dashboard' },
    isSystem: true,
  },
  {
    _id: 'm-au',
    name: 'SystemUsers',
    code: 'system:users',
    path: '/system/users',
    component: 'system/users/index',
    type: 'menu',
    icon: 'User',
    sort: 20,
    meta: { title: 'Users' },
    isSystem: true,
  },
  {
    _id: 'm-am',
    name: 'SystemMenus',
    code: 'system:menus',
    path: '/system/menus',
    component: 'system/menus/index',
    type: 'menu',
    icon: 'Menu',
    sort: 30,
    meta: { title: 'Menus' },
    isSystem: true,
  },
  {
    _id: 'm-ar',
    name: 'SystemRoles',
    code: 'system:roles',
    path: '/system/roles',
    component: 'system/roles/index',
    type: 'menu',
    icon: 'Avatar',
    sort: 40,
    meta: { title: 'Roles' },
    isSystem: true,
  },
  {
    _id: 'm-ai',
    name: 'SystemAiModel',
    code: 'system:ai-models',
    path: '/system/ai_model',
    component: 'system/ai_model/index',
    type: 'menu',
    icon: 'Cpu',
    sort: 50,
    meta: { title: 'AI Models' },
    isSystem: true,
  },
  {
    _id: 'm-td',
    name: 'TeacherDashboard',
    code: 'teacher:dashboard',
    path: '/teacher/dashboard',
    component: 'dashboard/TeacherDashboard',
    type: 'menu',
    icon: 'House',
    sort: 10,
    meta: { title: 'Teaching Center' },
    isSystem: true,
  },
  {
    _id: 'm-tc',
    name: 'TeacherClasses',
    code: 'teacher:classes',
    path: '/teacher/classes',
    component: 'teacher/classes/index',
    type: 'menu',
    icon: 'Reading',
    sort: 20,
    meta: { title: 'Class Management' },
    isSystem: true,
  },
  {
    _id: 'm-tc-detail',
    name: 'TeacherClassDetail',
    code: 'teacher:class-detail',
    path: '/teacher/classes-detail',
    component: 'teacher/classes/detail/index',
    type: 'menu',
    icon: 'Reading',
    sort: 21,
    hidden: true,
    meta: { title: 'Class Detail', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ta',
    name: 'TeacherAssignments',
    code: 'teacher:assignments',
    path: '/teacher/assignments',
    component: 'teacher/assignments/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 30,
    meta: { title: 'Assignments' },
    isSystem: true,
  },
  {
    _id: 'm-ta-edit',
    name: 'TeacherAssignmentEdit',
    code: 'teacher:assignment-edit',
    path: '/teacher/assignmentsEdit',
    component: 'teacher/assignments/assigmentsEidt/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 31,
    hidden: true,
    meta: { title: 'Create Assignment', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ta-detail',
    name: 'TeacherAssignmentDetail',
    code: 'teacher:assignment-detail',
    path: '/teacher/assignments/detail',
    component: 'teacher/assignments/detail/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 32,
    hidden: true,
    meta: { title: 'Assignment Detail', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-tr',
    name: 'TeacherAiRules',
    code: 'teacher:ai-rules',
    path: '/teacher/ai-rules',
    component: 'teacher/ai-rules/index',
    type: 'menu',
    icon: 'Setting',
    sort: 40,
    meta: { title: 'AI Rules' },
    isSystem: true,
  },
  {
    _id: 'm-treview',
    name: 'TeacherCorrecting',
    code: 'teacher:correcting',
    path: '/teacher/correcting',
    component: 'teacher/correcting/index',
    type: 'menu',
    icon: 'DocumentChecked',
    sort: 50,
    meta: { title: 'Reviews' },
    isSystem: true,
  },
  {
    _id: 'm-sd',
    name: 'StudentDashboard',
    code: 'student:dashboard',
    path: '/student/dashboard',
    component: 'dashboard/StudentDashboard',
    type: 'menu',
    icon: 'House',
    sort: 10,
    meta: { title: 'Study Center' },
    isSystem: true,
  },
  {
    _id: 'm-sc',
    name: 'StudentClasses',
    code: 'student:classes',
    path: '/student/classes',
    component: 'student/classes/index',
    type: 'menu',
    icon: 'Reading',
    sort: 20,
    meta: { title: 'My Classes' },
    isSystem: true,
  },
  {
    _id: 'm-sa',
    name: 'StudentAssignments',
    code: 'student:assignments',
    path: '/student/assignments',
    component: 'student/assignments/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 30,
    meta: { title: 'My Assignments' },
    isSystem: true,
  },
  {
    _id: 'm-sa-detail',
    name: 'StudentAssignmentDetail',
    code: 'student:assignment-detail',
    path: '/student/assignments/detail',
    component: 'student/assignments/detail',
    type: 'menu',
    icon: 'EditPen',
    sort: 31,
    hidden: true,
    meta: { title: 'Assignment Detail', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ss',
    name: 'StudentSubmissions',
    code: 'student:submissions',
    path: '/student/submissions',
    component: 'student/submissions/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 32,
    hidden: true,
    meta: { title: 'Submission Detail', hidden: true },
    isSystem: true,
  },
];

export const SYSTEM_ROLES = [
  {
    _id: 'r-admin',
    name: 'Super Admin',
    code: 'superadmin',
    description: 'System administrator',
    status: 'active' as const,
    isSystem: true,
    permissions: ['system:manage'],
    menuIds: ['m-ad', 'm-au', 'm-am', 'm-ar', 'm-ai'],
  },
  {
    _id: 'r-teacher',
    name: 'Teacher',
    code: 'teacher',
    description: 'Teacher role',
    status: 'active' as const,
    isSystem: true,
    permissions: [
      'class:view',
      'class:manage',
      'assignment:create',
      'assignment:view',
      'submission:review',
      'ai_rule:manage',
    ],
    menuIds: ['m-td', 'm-tc', 'm-tc-detail', 'm-ta', 'm-ta-edit', 'm-ta-detail', 'm-tr', 'm-treview'],
  },
  {
    _id: 'r-student',
    name: 'Student',
    code: 'student',
    description: 'Student role',
    status: 'active' as const,
    isSystem: true,
    permissions: ['assignment:view', 'submission:create', 'class:view'],
    menuIds: ['m-sd', 'm-sc', 'm-sa', 'm-sa-detail', 'm-ss'],
  },
];
