export const SYSTEM_MENUS = [
  {
    _id: 'm-ad',
    name: 'AdminDashboard',
    code: 'dashboard:admin',
    path: '/admin/dashboard',
    component: 'dashboard/AdminDashboard',
    type: 'menu',
    icon: 'Setting',
    sort: 10,
    meta: { title: '系统概览' },
    isSystem: true,
  },
  {
    _id: 'm-au',
    name: 'SystemUsers',
    code: 'system:users',
    path: '/system/users',
    component: 'system/users/index',
    type: 'menu',
    icon: 'User',
    sort: 20,
    meta: { title: '用户管理' },
    isSystem: true,
  },
  {
    _id: 'm-au-detail',
    name: 'SystemUserDetail',
    code: 'system:user-detail',
    path: '/system/users/:id',
    component: 'system/users/detail/index',
    type: 'menu',
    icon: 'User',
    sort: 21,
    hidden: true,
    meta: { title: '用户详情', hidden: true, activeMenu: '/system/users' },
    isSystem: true,
  },
  {
    _id: 'm-am',
    name: 'SystemMenus',
    code: 'system:menus',
    path: '/system/menus',
    component: 'system/menus/index',
    type: 'menu',
    icon: 'Menu',
    sort: 30,
    meta: { title: '菜单管理' },
    isSystem: true,
  },
  {
    _id: 'm-ar',
    name: 'SystemRoles',
    code: 'system:roles',
    path: '/system/roles',
    component: 'system/roles/index',
    type: 'menu',
    icon: 'Avatar',
    sort: 40,
    meta: { title: '角色管理' },
    isSystem: true,
  },
  {
    _id: 'm-ai',
    name: 'SystemAiModel',
    code: 'system:ai-models',
    path: '/system/ai_model',
    component: 'system/ai_model/index',
    type: 'menu',
    icon: 'Cpu',
    sort: 50,
    meta: { title: 'AI 模型' },
    isSystem: true,
  },
  {
    _id: 'm-td',
    name: 'TeacherDashboard',
    code: 'teacher:dashboard',
    path: '/teacher/dashboard',
    component: 'dashboard/TeacherDashboard',
    type: 'menu',
    icon: 'House',
    sort: 10,
    meta: { title: '教学中心' },
    isSystem: true,
  },
  {
    _id: 'm-tc',
    name: 'TeacherClasses',
    code: 'teacher:classes',
    path: '/teacher/classes',
    component: 'teacher/classes/index',
    type: 'menu',
    icon: 'Reading',
    sort: 20,
    meta: { title: '班级管理' },
    isSystem: true,
  },
  {
    _id: 'm-tc-detail',
    name: 'TeacherClassDetail',
    code: 'teacher:class-detail',
    path: '/teacher/classes-detail',
    component: 'teacher/classes/detail/index',
    type: 'menu',
    icon: 'Reading',
    sort: 21,
    hidden: true,
    meta: { title: '班级详情', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ta',
    name: 'TeacherAssignments',
    code: 'teacher:assignments',
    path: '/teacher/assignments',
    component: 'teacher/assignments/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 30,
    meta: { title: '作业管理' },
    isSystem: true,
  },
  {
    _id: 'm-ta-edit',
    name: 'TeacherAssignmentEdit',
    code: 'teacher:assignment-edit',
    path: '/teacher/assignmentsEdit',
    component: 'teacher/assignments/assigmentsEidt/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 31,
    hidden: true,
    meta: { title: '创建作业', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ta-detail',
    name: 'TeacherAssignmentDetail',
    code: 'teacher:assignment-detail',
    path: '/teacher/assignments/detail',
    component: 'teacher/assignments/detail/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 32,
    hidden: true,
    meta: { title: '作业详情', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-tr',
    name: 'TeacherAiRules',
    code: 'teacher:ai-rules',
    path: '/teacher/ai-rules',
    component: 'teacher/ai-rules/index',
    type: 'menu',
    icon: 'Setting',
    sort: 40,
    meta: { title: 'AI 规则' },
    isSystem: true,
  },
  {
    _id: 'm-treview',
    name: 'TeacherCorrecting',
    code: 'teacher:correcting',
    path: '/teacher/correcting',
    component: 'teacher/correcting/index',
    type: 'menu',
    icon: 'DocumentChecked',
    sort: 50,
    meta: { title: '批改中心' },
    isSystem: true,
  },
  {
    _id: 'm-sd',
    name: 'StudentDashboard',
    code: 'student:dashboard',
    path: '/student/dashboard',
    component: 'dashboard/StudentDashboard',
    type: 'menu',
    icon: 'House',
    sort: 10,
    meta: { title: '学习中心' },
    isSystem: true,
  },
  {
    _id: 'm-sc',
    name: 'StudentClasses',
    code: 'student:classes',
    path: '/student/classes',
    component: 'student/classes/index',
    type: 'menu',
    icon: 'Reading',
    sort: 20,
    meta: { title: '我的班级' },
    isSystem: true,
  },
  {
    _id: 'm-sa',
    name: 'StudentAssignments',
    code: 'student:assignments',
    path: '/student/assignments',
    component: 'student/assignments/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 30,
    meta: { title: '我的作业' },
    isSystem: true,
  },
  {
    _id: 'm-sa-detail',
    name: 'StudentAssignmentDetail',
    code: 'student:assignment-detail',
    path: '/student/assignments/detail',
    component: 'student/assignments/detail',
    type: 'menu',
    icon: 'EditPen',
    sort: 31,
    hidden: true,
    meta: { title: '作业详情', hidden: true },
    isSystem: true,
  },
  {
    _id: 'm-ss',
    name: 'StudentSubmissions',
    code: 'student:submissions',
    path: '/student/submissions',
    component: 'student/submissions/index',
    type: 'menu',
    icon: 'EditPen',
    sort: 32,
    hidden: true,
    meta: { title: '提交详情', hidden: true },
    isSystem: true,
  },
];

export const SYSTEM_ROLES = [
  {
    _id: 'r-admin',
    name: 'Super Admin',
    code: 'superadmin',
    description: 'System administrator',
    status: 'active' as const,
    isSystem: true,
    permissions: ['system:manage'],
    menuIds: ['m-ad', 'm-au', 'm-au-detail', 'm-am', 'm-ar', 'm-ai'],
  },
  {
    _id: 'r-teacher',
    name: 'Teacher',
    code: 'teacher',
    description: 'Teacher role',
    status: 'active' as const,
    isSystem: true,
    permissions: [
      'class:view',
      'class:manage',
      'assignment:create',
      'assignment:view',
      'submission:review',
      'ai_rule:manage',
    ],
    menuIds: [
      'm-td',
      'm-tc',
      'm-tc-detail',
      'm-ta',
      'm-ta-edit',
      'm-ta-detail',
      'm-tr',
      'm-treview',
    ],
  },
  {
    _id: 'r-student',
    name: 'Student',
    code: 'student',
    description: 'Student role',
    status: 'active' as const,
    isSystem: true,
    permissions: ['assignment:view', 'submission:create', 'class:view'],
    menuIds: ['m-sd', 'm-sc', 'm-sa', 'm-sa-detail', 'm-ss'],
  },
];
