server {
    listen 80;
    listen [::]:80;
    server_name yosem.vip www.yosem.vip;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 200 "Ready for Certbot challenge";
    }
}
